plugins {
    id 'net.neoforged.moddev' version '2.0.141'
}

base {
    archivesName = "${mod_id}-common"
}

neoForge {
    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
}

dependencies {
    compileOnly "com.cobblemon:neoforge:${cobblemon_version}"
    compileOnly "maven.modrinth:cobblemon-mega-showdown:${mega_showdown_version}"
    compileOnly "io.wispforest:accessories-neoforge:${accessories_version}"
    compileOnly "dev.architectury:architectury-neoforge:${architectury_version}"
    compileOnly "org.jetbrains.kotlin:kotlin-stdlib:1.9.22"

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
