package com.bigbang_tournaments.model;

public enum TournamentRuleViolationType {
    EMPTY_SLOT,
    EMPTY_PARTY,
    DUPLICATED_SPECIES,
    DUPLICATED_HELD_ITEM,
    BANNED_LEGENDARY,
    BANNED_MYTHICAL,
    BANNED_SPECIES,
    BANNED_ITEM,
    INVALID_LEVEL,
    MULTIPLE_SPECIAL_MECHANICS,
    DISALLOWED_SPECIAL_MECHANIC,
    ROSTER_CHANGED_AFTER_LOCK
}
